### ISSUE TITLE
Can't reach Solana or Ethereum endpoints when using docker-compose-test.yml

### ISSUE THREAD

**Issue by kevinji** [neonevm/proxy-model.py#1073]
I tried spinning up a local test environment using the `docker-compose-test.yml` file by running
```
USER@BOX:~/neon# REVISION=stable docker-compose -f docker-compose-test.yml up -d --quiet-pull
Creating network "neon_net" with the default driver
Creating solana   ... done
Creating postgres ... done
Creating evm_loader ... done
Creating indexer    ... done
Creating proxy      ... done
Creating faucet     ... done
Creating airdropper ... done
```
per the [docs website](https://docs.neon-labs.org/docs/developing/dev_environment/op2_local_proxy_local_solana), but I'm unable to reach either the Solana or the Ethereum endpoints:
```
USER@BOX:~/neon# curl -X GET http://localhost:8899/health
curl: (7) Failed to connect to localhost port 8899 after 0 ms: Connection refused
USER@BOX:~/neon# curl -X POST -H "Content-Type: application/json" --data '{ "jsonrpc": "2.0", "method": "eth_blockNumber", "id": 126, "params": [] }' http://localhost:9090/solana
curl: (52) Empty reply from server
```

Is there any way to debug what's going on?

**Comment by neelsomani** [comment]
I tried reproducing and run into the same error. When I look at the Docker logs for the proxy I see this:
```
[...]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA==", "base64"], "executable": false, "lamports": 5143821440, "owner": "gSbePebfvPy7tRqimPoVecS2UsBvYv46ynrzWocc92s", "rentEpoch": 371}}}
2023-02-07 03:40:36.200 D solana_interactor.py:197 639 Proxy:SolanaInteractor {} {"error": {"code": -32602, "message": "Too many inputs provided; max 100"}, "id": 2, "jsonrpc": "2.0"}
2023-02-07 03:40:36.200 E handler.py:413 639 proxy.http.handler:Undefined {} Exception while handling connection <socket.socket fd=49, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('172.18.0.5', 9090), raddr=('172.18.0.1', 55754)>
Traceback (most recent call last):
  File "/opt/proxy/http/handler.py", line 397, in run
    self.initialize()
  File "/opt/proxy/http/handler.py", line 138, in initialize
    instance = klass(
  File "/opt/proxy/http/server/web.py", line 68, in __init__
    instance = klass(
  File "/usr/local/lib/python3.8/dist-packages/logged_groups/logging.py", line 156, in __init__
    orig_init(self, *args, **kws)
  File "/opt/proxy/plugin/solana_rest_api.py", line 406, in __init__
    self.model = SolanaProxyPlugin.getModel()
  File "/opt/proxy/plugin/solana_rest_api.py", line 414, in getModel
    modelInstance = EthereumModel()
  File "/usr/local/lib/python3.8/dist-packages/logged_groups/logging.py", line 156, in __init__
    orig_init(self, *args, **kws)
  File "/opt/proxy/plugin/solana_rest_api.py", line 61, in __init__
    self.gas_price_calculator.update_mapping()
  File "/opt/proxy/plugin/gas_price_calculator.py", line 26, in update_mapping
    self.pyth_network_client.update_mapping(self.mapping_account)
  File "/opt/proxy/indexer/pythnetwork.py", line 172, in update_mapping
    products = self.read_pyth_acct_data(product_accts)
  File "/opt/proxy/indexer/pythnetwork.py", line 119, in read_pyth_acct_data
    acct_values = self.solana.get_account_info_list(acc_addrs, length=0)
  File "/opt/proxy/common_neon/solana_interactor.py", line 199, in get_account_info_list
    if result['result']['value'] is None:
KeyError: 'result'
```

**Comment by arkadyone** [comment]
@thespamer  please look at this issue

**Comment by thespamer** [comment]
The issue is related to a limit from Solana devnet to handle only 100 requests per source IP. -> https://api.devnet.solana.com
https://docs.solana.com/cluster/rpc-endpoints#devnet

In order to test it properly, you need to setup your own Solana RPC endpoint and set your SOLANA_URL in docker-compose-test.yml

**Comment by neelsomani** [comment]
Isn't that what the local Neon image does? I see it spins up a fresh local Solana cluster.

I see that the Pyth file which is responsible for this error is no longer present in the development branch.

I think the Docker compose file should be able to be run right out of the box, maybe we can work to resolve this since this is referenced in the Neon docs.

Thank you!

**Comment by thespamer** [comment]
Please @neelsomani, update the file from repository and use this command with latest version:

host#wget https://raw.githubusercontent.com/neonlabsorg/proxy-model.py/master/proxy/docker-compose-test.yml

host# sudo FAUCET_COMMIT=latest  NEON_EVM_COMMIT=latest REVISION=latest docker-compose -f docker-compose-test.yml up -d --quiet-pull

...
..
.

host# curl -X POST -H "Content-Type: application/json" --data '{ "jsonrpc": "2.0", "method": "eth_blockNumber", "id": 126, "params": [] }' http://localhost:9090/solana
{"jsonrpc": "2.0", "id": 126, "result": "0x255"}

host# curl -X GET http://localhost:8899/health
ok

**Comment by kevinji** [comment]
Going to close as resolved via @thespamer's command, thanks.
