### ISSUE TITLE
Invalid account data when deploy Uniswap periphery contracts

### ISSUE THREAD

**Issue by s-medvedev** [neonevm/proxy-model.py#198]
**STR:**
Try to deploy small contracts from Remix

**Actual result:**
Deploy failed with error `Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32002,"message":"Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction","data":{"accounts":null,"err":{"InstructionError":[0,"InvalidAccountData"]},"logs":["Program eeLSJgWzzxrqKv1UxtRVVH8FX3qCQWUs9QuAjJpETGU invoke [1]","Program log: src/storage_account.rs:65","Program eeLSJgWzzxrqKv1UxtRVVH8FX3qCQWUs9QuAjJpETGU consumed 5335 of 500000 compute units","Program eeLSJgWzzxrqKv1UxtRVVH8FX3qCQWUs9QuAjJpETGU failed: invalid account data for instruction"]}}}}'`

**Expected result:**
Successful deploy

**Additional info:**
Proxy logs:
```
2021-09-16 17:11:12,580 - pid:170 [E] __post_send:1085 - {'code': -32002, 'message': 'Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction', 'data': {'accounts': None, 'err': {'InstructionError': [0, 'InvalidAccountData']}, 'logs': ['Program eeLSJgWzzxrqKv1UxtRVVH8FX3qCQWUs9QuAjJpETGU invoke [1]', 'Program log: src/storage_account.rs:65', 'Program eeLSJgWzzxrqKv1UxtRVVH8FX3qCQWUs9QuAjJpETGU consumed 5335 of 500000 compute units', 'Program eeLSJgWzzxrqKv1UxtRVVH8FX3qCQWUs9QuAjJpETGU failed: invalid account data for instruction']}}
2021-09-16 17:11:12,580 - pid:170 [D] eth_sendRawTransaction:402 - eth_sendRawTransaction solana.rpc.api.SendTransactionError:{'code': -32002, 'message': 'Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction', 'data': {'accounts': None, 'err': {'InstructionError': [0, 'InvalidAccountData']}, 'logs': ['Program eeLSJgWzzxrqKv1UxtRVVH8FX3qCQWUs9QuAjJpETGU invoke [1]', 'Program log: src/storage_account.rs:65', 'Program eeLSJgWzzxrqKv1UxtRVVH8FX3qCQWUs9QuAjJpETGU consumed 5335 of 500000 compute units', 'Program eeLSJgWzzxrqKv1UxtRVVH8FX3qCQWUs9QuAjJpETGU failed: invalid account data for instruction']}}
Traceback (most recent call last):
  File "/opt/proxy/plugin/solana_rest_api.py", line 516, in process_request
    response['result'] = method(*request['params'])
  File "/opt/proxy/plugin/solana_rest_api.py", line 384, in eth_sendRawTransaction
    (signature, contract_eth) = deploy_contract(self.signer, self.client, trx, self.perm_accs, steps=250)
  File "/opt/proxy/plugin/solana_rest_api_tools.py", line 919, in deploy_contract
    return (call_continue(signer, client, perm_accs, trx_accs, steps), '0x'+contract_eth.hex())
  File "/opt/proxy/plugin/solana_rest_api_tools.py", line 436, in call_continue
    return sol_instr_12_cancel(signer, client, perm_accs, trx_accs)
  File "/opt/proxy/plugin/solana_rest_api_tools.py", line 509, in sol_instr_12_cancel
    result = send_measured_transaction(client, trx, signer)
  File "/opt/proxy/plugin/solana_rest_api_tools.py", line 393, in send_measured_transaction
    result = send_transaction(client, trx, signer)
  File "/opt/proxy/plugin/solana_rest_api_tools.py", line 387, in send_transaction
    result = client.send_transaction(trx, signer, opts=TxOpts(skip_confirmation=True, preflight_commitment=Confirmed))
  File "/usr/local/lib/python3.8/dist-packages/solana/rpc/api.py", line 1017, in send_transaction
    return self.send_raw_transaction(txn.serialize(), opts=opts)
  File "/usr/local/lib/python3.8/dist-packages/solana/rpc/api.py", line 984, in send_raw_transaction
    return self.__post_send(resp, opts.skip_confirmation, opts.preflight_commitment)
  File "/usr/local/lib/python3.8/dist-packages/solana/rpc/api.py", line 1086, in __post_send
    raise SendTransactionError(resp.get("error"))
solana.rpc.api.SendTransactionError: Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction
2021-09-16 17:11:12,581 - pid:170 [D] handle_request:562 - >>> 140257026696960 0x7f9022442fd0 {"jsonrpc": "2.0", "id": 2664387197940, "error": {"code": -32002, "message": "Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction", "data": {"accounts": null, "err": {"InstructionError": [0, "InvalidAccountData"]}, "logs": ["Program eeLSJgWzzxrqKv1UxtRVVH8FX3qCQWUs9QuAjJpETGU invoke [1]", "Program log: src/storage_account.rs:65", "Program eeLSJgWzzxrqKv1UxtRVVH8FX3qCQWUs9QuAjJpETGU consumed 5335 of 500000 compute units", "Program eeLSJgWzzxrqKv1UxtRVVH8FX3qCQWUs9QuAjJpETGU failed: invalid account data for instruction"]}}}
```

**Comment by mich-master** [comment]
**The problem similar to:**
https://github.com/neonlabsorg/neon-evm/issues/237#issuecomment-921592872
https://github.com/neonlabsorg/neon-evm/issues/237#issuecomment-920835441
**Proxy log:**
> Traceback (most recent call last):
>   File "/opt/proxy/plugin/solana_rest_api.py", line 516, in process_request
>     response['result'] = method(*request['params'])
>   File "/opt/proxy/plugin/solana_rest_api.py", line 384, in eth_sendRawTransaction
>     (signature, contract_eth) = deploy_contract(self.signer, self.client, trx, self.perm_accs, steps=250)
>   File "/opt/proxy/plugin/solana_rest_api_tools.py", line 919, in deploy_contract
>     return (call_continue(signer, client, perm_accs, trx_accs, steps), '0x'+contract_eth.hex())
>   File "/opt/proxy/plugin/solana_rest_api_tools.py", line 436, in call_continue
>     return sol_instr_12_cancel(signer, client, perm_accs, trx_accs)
>   File "/opt/proxy/plugin/solana_rest_api_tools.py", line 509, in sol_instr_12_cancel
>     result = send_measured_transaction(client, trx, signer)
>   File "/opt/proxy/plugin/solana_rest_api_tools.py", line 393, in send_measured_transaction
>     result = send_transaction(client, trx, signer)
>   File "/opt/proxy/plugin/solana_rest_api_tools.py", line 387, in send_transaction
>     result = client.send_transaction(trx, signer, opts=TxOpts(skip_confirmation=True, preflight_commitment=Confirmed))
>   File "/usr/local/lib/python3.8/dist-packages/solana/rpc/api.py", line 1017, in send_transaction
>     return self.send_raw_transaction(txn.serialize(), opts=opts)
>   File "/usr/local/lib/python3.8/dist-packages/solana/rpc/api.py", line 984, in send_raw_transaction
>     return self.__post_send(resp, opts.skip_confirmation, opts.preflight_commitment)
>   File "/usr/local/lib/python3.8/dist-packages/solana/rpc/api.py", line 1086, in __post_send
>     raise SendTransactionError(resp.get("error"))
> solana.rpc.api.SendTransactionError: Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction
