### ISSUE TITLE
Call emulated:  PaymentSplitter.rejects an empty set of payees

### ISSUE THREAD

**Issue by rozhkovdmitrii** [neonevm/proxy-model.py#299]
### STR:

It can be reproduced either manually with open zeppelin testing like that:
```sh
$ truffle test test/finance/PaymentSplitter.test.js --network solana
```
- or it can be met during [night tests fulfilment](https://docs.neon-labs.org/neon-compatibility/70/#suites/8b624a411e4d42151c31614bc9fe5151/93d7ff4383f3c33a/)

### Expected result:

1) Contract: PaymentSplitter
       rejects an empty set of payees:

> PaymentSplitter in particular and neon evm endpoint should raise the error **"PaymentSplitter: no payees"**

### Actual result:

**"execution reverted"**

> `emulate_call` on proxy gets "revert" exit status and returns wrong result

### Full output:

```
Contract: PaymentSplitter
@openzeppelin/test-helpers WARN expectRevert: Assertions may yield false negatives!

Revert reason checks are only known to work on Ganache >=2.2.0 and Hardhat, and the current node is Neon/v0.3.0-rc1-a3a3cee.

If your node does support revert reasons, please let us know: https://github.com/OpenZeppelin/openzeppelin-test-helpers/issues/new
    1) rejects an empty set of payees
    2) "after each" hook: after test for "rejects an empty set of payees"


  0 passing (2s)
  2 failing

  1) Contract: PaymentSplitter
       rejects an empty set of payees:

      Wrong kind of exception received
      + expected - actual

      -execution reverted
      +PaymentSplitter: no payees
       
      at expectException (node_modules/@openzeppelin/test-helpers/src/expectRevert.js:20:30)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at expectRevert (node_modules/@openzeppelin/test-helpers/src/expectRevert.js:75:3)
      at Context.<anonymous> (test/finance/PaymentSplitter.test.js:15:5)

  2) Contract: PaymentSplitter
       "after each" hook: after test for "rejects an empty set of payees":
     Error: syntax error at or near ")"
LINE 1: ... blockNumber >= 2657 AND blockNumber <= 2657 AND topic IN ()
                                                                      ^

      at /home/rozhkov/sources/oz/node_modules/@trufflesuite/web3-provider-engine/subproviders/provider.js:18:36
      at XMLHttpRequest.request.onreadystatechange (node_modules/web3-providers-http/lib/index.js:98:13)
      at XMLHttpRequestEventTarget.dispatchEvent (node_modules/xhr2-cookies/xml-http-request-event-target.ts:44:13)
      at XMLHttpRequest._setReadyState (node_modules/xhr2-cookies/xml-http-request.ts:219:8)
      at XMLHttpRequest._onHttpResponseEnd (node_modules/xhr2-cookies/xml-http-request.ts:345:8)
      at IncomingMessage.<anonymous> (node_modules/xhr2-cookies/xml-http-request.ts:311:39)
      at IncomingMessage.emit (node:events:402:35)
      at endReadableNT (node:internal/streams/readable:1343:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by rozhkovdmitrii** [comment]
connected with #285

**Comment by rozhkovdmitrii** [comment]
Related links:

[Error processing. Solidity ABI](https://docs.soliditylang.org/en/latest/control-structures.html#revert)
[Solidity contract ABI specification](https://docs.soliditylang.org/en/latest/abi-spec.html)
[Docs: Update solidity version for revert with reason #3885](https://github.com/ethereum/solidity/pull/3885)
[Revert with reason #3364](https://github.com/ethereum/solidity/pull/3364)

[Related Ethereum EIP](https://github.com/ethereum/EIPs/issues/838#issuecomment-458919375)
