### ISSUE TITLE
Concurrent execution of 'solana program dump' damages dump-file's data

### ISSUE THREAD

**Issue by ivandzen** [neonevm/proxy-model.py#313]
Bug oftenly occurs when very first client connection is going to be handled by proxy. Error description from logs:
`2021-11-19 13:14:24,771 - pid:61 [D] call:35 - Calling: neon-cli --commitment=recent --url http://solana:8899 --evm_loader=53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io neon-elf-params ./evm_loader.dump
thread 'main' panicked at 'Unable to parse ELF file: Scroll(BadOffset(0))', cli/src/main.rs:1176:53`

**Comment by ivandzen** [comment]
Example of logs:
`2021-11-19 13:14:24,714 - pid:61 [D] neon_config_load:455 - loading the neon config dict for the first time!
2021-11-19 13:14:24,714 - pid:61 [D] read_elf_params:43 - load for solana_url=http://solana:8899 and evm_loader_id=53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io
2021-11-19 13:14:24,714 - pid:61 [D] call:19 - Calling: solana --url http://solana:8899 program dump 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io ./evm_loader.dump
2021-11-19 13:14:24,718 - pid:51 [D] __init__:64 - worker id 8
2021-11-19 13:14:24,718 - pid:51 [D] neon_config_load:455 - loading the neon config dict for the first time!
2021-11-19 13:14:24,719 - pid:51 [D] read_elf_params:43 - load for solana_url=http://solana:8899 and evm_loader_id=53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io
2021-11-19 13:14:24,719 - pid:51 [D] call:19 - Calling: solana --url http://solana:8899 program dump 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io ./evm_loader.dump
2021-11-19 13:14:24,751 - pid:65 [D] __init__:64 - worker id 9
2021-11-19 13:14:24,751 - pid:65 [D] neon_config_load:455 - loading the neon config dict for the first time!
2021-11-19 13:14:24,751 - pid:65 [D] read_elf_params:43 - load for solana_url=http://solana:8899 and evm_loader_id=53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io
2021-11-19 13:14:24,751 - pid:65 [D] call:19 - Calling: solana --url http://solana:8899 program dump 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io ./evm_loader.dump
2021-11-19 13:14:24,757 - pid:49 [D] call:35 - Calling: neon-cli --commitment=recent --url http://solana:8899 --evm_loader=53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io neon-elf-params ./evm_loader.dump
2021-11-19 13:14:24,768 - pid:47 [D] call:35 - Calling: neon-cli --commitment=recent --url http://solana:8899 --evm_loader=53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io neon-elf-params ./evm_loader.dump
2021-11-19 13:14:24,771 - pid:53 [D] call:35 - Calling: neon-cli --commitment=recent --url http://solana:8899 --evm_loader=53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io neon-elf-params ./evm_loader.dump
2021-11-19 13:14:24,771 - pid:61 [D] call:35 - Calling: neon-cli --commitment=recent --url http://solana:8899 --evm_loader=53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io neon-elf-params ./evm_loader.dump
thread 'main' panicked at 'Unable to parse ELF file: Scroll(BadOffset(0))', cli/src/main.rs:1176:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2021-11-19 13:14:24,779 - pid:49 [D] call:39 - ERR: neon-cli error Command '['neon-cli', '--commitment=recent', '--url', 'http://solana:8899', '--evm_loader=53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io', 'neon-elf-params', './evm_loader.dump']' returned non-zero exit status 101.
2021-11-19 13:14:24,779 - pid:49 [E] run:413 - Exception while handling connection <socket.socket fd=25, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('172.19.0.4', 9090), raddr=('172.19.0.1', 38966)>
Traceback (most recent call last):
  File "/opt/proxy/http/handler.py", line 397, in run
    self.initialize()
  File "/opt/proxy/http/handler.py", line 138, in initialize
    instance = klass(
  File "/opt/proxy/http/server/web.py", line 68, in __init__
    instance = klass(
  File "/opt/proxy/plugin/solana_rest_api.py", line 565, in __init__
    self.model = SolanaProxyPlugin.getModel()
  File "/opt/proxy/plugin/solana_rest_api.py", line 573, in getModel
    modelInstance = EthereumModel()
  File "/opt/proxy/plugin/solana_rest_api.py", line 66, in __init__
    neon_config_load(self)
  File "/opt/proxy/plugin/solana_rest_api_tools.py", line 463, in neon_config_load
    read_elf_params(ethereum_model.neon_config_dict)
  File "/opt/proxy/environment.py", line 52, in read_elf_params
    for param in neon_cli().call("neon-elf-params", path).splitlines():
  File "/opt/proxy/environment.py", line 36, in call
    return subprocess.check_output(cmd, timeout=neon_cli_timeout, universal_newlines=True)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['neon-cli', '--commitment=recent', '--url', 'http://solana:8899', '--evm_loader=53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io', 'neon-elf-params', './evm_loader.dump']' returned non-zero exit status 101.
thread 'main' panicked at 'Unable to parse ELF file: Scroll(BadOffset(0))', cli/src/main.rs:1176:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Unable to parse ELF file: Scroll(BadOffset(0))', cli/src/main.rs:1176:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Unable to parse ELF file: Scroll(BadOffset(0))', cli/src/main.rs:1176:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2021-11-19 13:14:24,786 - pid:61 [D] call:39 - ERR: neon-cli error Command '['neon-cli', '--commitment=recent', '--url', 'http://solana:8899', '--evm_loader=53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io', 'neon-elf-params', './evm_loader.dump']' returned non-zero exit status 101.
2021-11-19 13:14:24,786 - pid:47 [D] call:39 - ERR: neon-cli error Command '['neon-cli', '--commitment=recent', '--url', 'http://solana:8899', '--evm_loader=53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io', 'neon-elf-params', './evm_loader.dump']' returned non-zero exit status 101.
2021-11-19 13:14:24,787 - pid:53 [D] call:39 - ERR: neon-cli error Command '['neon-cli', '--commitment=recent', '--url', 'http://solana:8899', '--evm_loader=53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io', 'neon-elf-params', './evm_loader.dump']' returned non-zero exit status 101.`
