### ISSUE TITLE
Proxy returns empty message for empty revert

### ISSUE THREAD

**Issue by afalaleev** [neonevm/proxy-model.py#431]
**Impact:**
_Proxy + Neon EVM  <->  OpenZeppelin library compatibility
Safe math operations computation_

**STR:**
1. Set up environment for the OpenZeppelin library as described
[neon-compatibility](https://github.com/neonlabsorg/neon-compatibility)
2. Run the unit test for "SafeMath" contract
`npx hardhat test ./test/utils/math/SafeMath.test.js`

**Actual result:**
Error message

> Wrong kind of exception received
>      + expected - actual
>    -Returned error: {"id":1050,"jsonrpc":"2.0","error":{"code":3,"message":"","data":{"stack":"ProviderError: \n    at HttpProvider.request (/home/afalaleev/projects/solana/neon-compatibility/openzeppelin-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)\n    at LocalAccountsProvider.request (/home/afalaleev/projects/solana/neon-compatibility/openzeppelin-contracts/node_modules/hardhat/src/internal/core/providers/accounts.ts:187:34)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at Web3HTTPProviderAdapter._sendJsonRpcRequest (/home/afalaleev/projects/solana/neon-compatibility/openzeppelin-contracts/node_modules/@nomiclabs/hardhat-web3/src/web3-provider-adapter.ts:80:22)","name":"ProviderError"}}}
>      +revert

**Expected result:**
Test passed successfully.

**Additional info:**
The [ethereum node](https://github.com/ethereum/go-ethereum/blob/c10a0a62c3537fbcf899358e3c3d6be9507fa18c/internal/ethapi/api.go#L949-L959) returns _'execution reverted'_ in this case.

**Comment by afalaleev** [comment]
connected with #285
