### ISSUE TITLE
Neon-EVM doesn't support ERC1820 after EIP-155

### ISSUE THREAD

**Issue by afalaleev** [neonevm/proxy-model.py#559]
```2
    response['result'] = method(*params)
  File "/opt/proxy/plugin/solana_rest_api.py", line 369, in eth_sendRawTransaction
    tx_sender = NeonTxSender(self._db, self._client, trx, steps=500)
  File "/usr/local/lib/python3.8/dist-packages/logged_groups/logging.py", line 156, in __init__
    orig_init(self, *args, **kws)
  File "/opt/proxy/common_neon/transaction_sender.py", line 382, in __init__
    self.eth_sender = '0x' + eth_tx.sender()
  File "/opt/proxy/common_neon/eth_proto.py", line 66, in sender
    return self._sender().hex()
  File "/opt/proxy/common_neon/eth_proto.py", line 60, in _sender
    hash = keccak_256(self.unsigned_msg()).digest()
  File "/opt/proxy/common_neon/eth_proto.py", line 53, in unsigned_msg
    self._msg = rlp.encode((self.nonce, self.gasPrice, self.gasLimit, self.toAddress, self.value, self.callData, self.chainId(), b"", b""))
  File "/usr/local/lib/python3.8/dist-packages/rlp/codec.py", line 63, in encode
    item = infer_sedes(obj).serialize(obj)
  File "/usr/local/lib/python3.8/dist-packages/rlp/codec.py", line 278, in infer_sedes
    return List(map(infer_sedes, obj))
  File "/usr/local/lib/python3.8/dist-packages/rlp/sedes/lists.py", line 53, in __init__
    for e in elements:
  File "/usr/local/lib/python3.8/dist-packages/rlp/codec.py", line 284, in infer_sedes
    raise TypeError(msg)
```

┆Issue is synchronized with this [Jira Task](https://neonlabs.atlassian.net/browse/NEON-254) by [Unito](https://www.unito.io)

**Comment by afalaleev** [comment]
```env PRIVATE_KEYS=$(./get_private_keys.js) ./node_modules/.bin/hardhat test ./test/utils/introspection/ERC1820Implementer.test.js```

**Comment by vasiliy-zaznobin** [comment]
Can't reproduce the problem.
I have another one:
  Contract: ERC1820Implementer
    with no registered interfaces
      1) "before each" hook for "returns false when interface implementation is queried"


  0 passing (3s)
  1 failing

  1) Contract: ERC1820Implementer
       "before each" hook for "returns false when interface implementation is queried":
     Error: Returned error: **Expecting value: line 1 column 1 (char 0)**
      at Object.ErrorResponse (/home/vzaznobin/neon/neon-compatibility/node_modules/web3-core-requestmanager/node_modules/web3-core-helpers/lib/errors.js:28:19)
      at /home/vzaznobin/neon/neon-compatibility/node_modules/web3-core-requestmanager/lib/index.js:302:36
      at processTicksAndRejections (node:internal/process/task_queues:83:21)
      
```
2022-02-09 13:14:54.491 E solana_rest_api.py:506 623 Proxy:SolanaProxyPlugin {"req_id": "cb3052c"} Exception on process request. Type(err): <class 'json.decoder.JSONDecodeError'>, Error: Expecting value: line 1 column 1 (char 0), Traceback:   File "/opt/proxy/plugin/solana_rest_api.py", line 497, in process_request
    response['result'] = method(*params)
  File "/opt/proxy/plugin/solana_rest_api.py", line 370, in eth_sendRawTransaction
    tx_sender.execute()
  File "/opt/proxy/common_neon/transaction_sender.py", line 400, in execute
    self._prepare_execution()
  File "/opt/proxy/common_neon/transaction_sender.py", line 496, in _prepare_execution
    self._call_emulated()
  File "/opt/proxy/common_neon/transaction_sender.py", line 522, in _call_emulated
    self._emulator_json = call_emulated(dst, src, self.eth_tx.callData.hex(), hex(self.eth_tx.value))
  File "/usr/local/lib/python3.8/dist-packages/logged_groups/logging.py", line 167, in inner_wrapper
    return original_function(*args, **kwargs)
  File "/opt/proxy/common_neon/emulator_interactor.py", line 13, in call_emulated
    result = json.loads(output)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

2022-02-09 13:14:54.491 I solana_rest_api.py:555 623 Proxy:SolanaProxyPlugin {"req_id": "cb3052c"} handle_request >>> 140312468006656 0x7f9d0bd09610 {"jsonrpc": "2.0", "id": 12, "error": {"code": -32000, "message": "Expecting value: line 1 column 1 (char 0)"}} eth_sendRawTransaction resp_time_ms= 357.2380542755127
2022-02-09 13:14:54.491 I solana_rest_api.py:516 623 Proxy:SolanaProxyPlugin {"req_id": "cb3052c"} Request processed
```

**Comment by vasiliy-zaznobin** [comment]
https://github.com/neonlabsorg/proxy-model.py/issues/562

**Comment by vasiliy-zaznobin** [comment]
The main problem is that after the introduction of [EIP-155](https://eips.ethereum.org/EIPS/eip-155), neon-evm stopped accepting transactions without specifying a chain ID. And now Neon-EVM doesn't support [ERC1820](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1820.md#deployment-method)

To support ERC1820 [here](https://github.com/neonlabsorg/proxy-model.py/blob/develop/proxy/common_neon/eth_proto.py#L53) Neon-Proxy should use only 6 fields to create an unsigned_msg

If change Neon-Proxy like this:
```python
    def chainId(self):
        # chainid*2 + 35  xxxxx0 + 100011   xxxx0 + 100010 +1
        # chainid*2 + 36  xxxxx0 + 100100   xxxx0 + 100011 +1
        # check that is not ERC-155
        if self.v < 35:
            return None
        return (self.v-1)//2 - 17

    def unsigned_msg(self):
        if self._msg is None:
            if self.chainId() is None:
                self.debug(f'Creating unsigned_msg from nonce={self.nonce}; gasPrice={self.gasPrice}; gasLimit={self.gasLimit}; toAddress={self.toAddress}; value={self.value}; callData={str(self.callData)};')
                self._msg = rlp.encode((self.nonce, self.gasPrice, self.gasLimit, self.toAddress, self.value, self.callData))
            else:
                self.debug(f'Creating unsigned_msg from nonce={self.nonce}; gasPrice={self.gasPrice}; gasLimit={self.gasLimit}; toAddress={self.toAddress}; value={self.value}; callData={str(self.callData)}; self.chainId()={self.chainId()}')
                self._msg = rlp.encode((self.nonce, self.gasPrice, self.gasLimit, self.toAddress, self.value, self.callData, self.chainId(), b"", b""))
        return self._msg
```

the following error is occurred:
```
2022-02-10 11:54:02.352 E solana_rest_api.py:378 389 Proxy:EthereumModel {"req_id": "7a16cf6"} Got SendTransactionError: {
   "code": -32002,
   "message": "Transaction simulation failed: Error processing Instruction 0: invalid instruction data",
   "data": {
      "accounts": null,
      "err": {
         "InstructionError": [
            0,
            "InvalidInstructionData"
         ]
      },
      "logs": [
         "Program 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io invoke [1]",
         "Program log: program/src/storage_account.rs:75",
         "Program log: program/src/entrypoint.rs:604 : DecoderError=RlpIncorrectListLen",
         "Program 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io consumed 36146 of 500000 compute units",
         "Program 53DfF883gyixYNXnM7s5xhdeyV8mVk9T4i2hGV9vG9io failed: invalid instruction data"
      ]
   }
}

``` 
So Neon-EVM should be changed too

**Comment by vasiliy-zaznobin** [comment]
This will be fixed after launch in the mainnet
